### PR TITLE
Data freshness

### PR DESCRIPTION
**Pull request by tallywiesenberg**
Added data freshness implementaiton using two new workflow variables and day.js module. The new functionality exits early if the user tolerates the age of the requestID's data. If the data is not fresh enough, the tip is submitted.

### CODE REVIEW

**Review by brendaloya — COMMENTED** [review]
Hi Tally, Overall, this repo is looking great! I did a quick review and I'm wondering if this is what you intended with the new check. I think it would be more useful combined with a check if it is or if it is not on queue if the time being checked is truly just the timestamp of the last tip, not the last time it was mined(added on chain).

Can you add a note about where the input variables come from on the readme(tipperTemplate) and a brief description of why this exists?

Also, can you walk me through line 148.  should it be "<"?  here is the example I walked myself through. 


  | now | specified   freshness
-- | -- | --
  | 2pm | 30min
  |   |  
if(dayjs().subtract(freshnessTimeLength,   freshnessTimeUnit) > lastTipTimestamp , don’t tip…
  | dayjs-freshness | last tip   time
example   with time | 130pm              > | 12pm
example   with day | 23-Mar             > | 21-Mar
  | else(tip) |  
example   with time | 130pm              < | 140pm
example   with day | 23-Mar             < | 22-Mar

**Comment by tallywiesenberg** [comment]
Ok, I corrected the sign and renamed the timestamp variable on line 148. When you mention a readme, do you mean the tipper readme, or the tippertemplate readme?

**Review by brendaloya — APPROVED** [review]

**Comment by brendaloya** [comment]
> Ok, I corrected the sign and renamed the timestamp variable on line 148. When you mention a readme, do you mean the tipper readme, or the tippertemplate readme?

I meant here in the tipper repo's readme so that in the future *devs know these two repos are related and that tipper is basically the backbone of the tippertemplate.

**Comment by tallywiesenberg** [comment]
Hey! I edited the expected inputs on the action.yml file to match the inputs that the tipper script accepts. @brendaloya

**Pull request merged**
